:building_construction: Created the Jira Assets module
ctreminiom/go-atlassian pull request #204
Opened 2023-05-28 06:39 UTC by ctreminiom

1. Created the service interfaces for the Assets icons,AQL, and object's.

2023-05-30 21:56 UTC, Fank requested changes

2023-05-30 21:56 UTC, Fank commented on service/assets/icon.go
> +	Global(ctx context.Context, workspaceID string) (*[]models.IconAssetScheme, *models.ResponseScheme, error)
You are using a pointer before the array, compared to the code in service/assets/object.go it looks like it should be
```suggestion
	Global(ctx context.Context, workspaceID string) ([]*models.IconAssetScheme, *models.ResponseScheme, error)
```

2023-06-09 01:57 UTC, ctreminiom commented
@Fank the first version of the Jira Assets implementation is now operative!, I tested and document each endpoint and it works as expected. 

But, as I'm not a Jira Asset expert, could you please test the methods and provide some feedback about the module?

The documentation is hosted at https://docs.go-atlassian.io/jira-assets/overview

_Pura Vida_

2023-06-09 11:57 UTC, Fank commented
Thanks @ctreminiom

I started replacing everything in our code so far, but ran into some issues i opened in seperate issues here.
I will just replace assets and give you feedback about it soon as i can, expect ~2 weeks.
Keep the PR open, i will comment about everything i find.

2023-06-13 19:48 UTC, Fank requested changes

2023-06-13 19:48 UTC, Fank commented on service/assets/aql.go
> +	// https://docs.go-atlassian.io/jira-assets/aql#filter-objects
```suggestion
	// Filter retrieves a list of objects based on an AQL. Note that the preferred endpoint is /aql.
	//
	// POST /jsm/assets/workspace/{workspaceId}/v1/object/navlist/aql
	//
	// https://docs.go-atlassian.io/jira-assets/aql#filter-objects
	// Deprecated: Use ObjectConnector.Filter instead.
```

2023-06-13 19:48 UTC, Fank commented on service/assets/object.go
> +}
```suggestion

	// Filter fetch Objects by AQL.
	//
	// POST /jsm/assets/workspace/{workspaceId}/v1/object/aql
	//
	// https://docs.go-atlassian.io/jira-assets/objects#filter-objects
	Filter(ctx context.Context, workspaceID string, payload *models.ObjectsAQLSearchParamsScheme) (*models.ObjectScheme, *models.ResponseScheme, error)
}
```

2023-06-13 19:48 UTC, Fank commented on service/assets/aql.go
> +	// https://docs.go-atlassian.io/jira-assets/aql#filter-objects
![image](https://github.com/ctreminiom/go-atlassian/assets/1900106/722e40dd-10a5-4b00-a436-c393b9a5d73b)

2023-06-14 18:08 UTC, ctreminiom commented
> @ctreminiom it would be nice if you could provide some functions for checking errors, like in the case i had before:
> 
> ```go
> assetObject, err = jiraClient.Assets.Object.Get(ctx, jiraAssetsWorkspaceID, jiraAssetsID)
> if err != nil && !errors.Is(err, cloud.ErrNotFound) {
> 	return err
> }
> ```
> 
> Currently it would looks like
> 
> ```go
> assetObject, response, err := jiraAssetsClient.Object.Get(ctx, jiraAssetsWorkspaceID, jiraAssetsID)
> if err != nil && response.StatusCode != http.StatusNotFound {
> 	return err
> }
> ```
> 
> Its is not that bad, just wondering how you would handle such error cases? In this situation I want to check on an `Object.Get` if it exists if yes `Object.Update` if not `Object.Create`.

_________________

Hi @Fank, it's because there's a possibility the HTTP call should return an error `(timeout error)` and the _Call()_ method does not return the response struct due to the callback returns nothing.

But, I can put more logic on the HTTP implementation and manipulate the errors based on the HTTP status code so the error `cloud.ErrNotFound` can be used on the other modules.

2023-06-20 18:04 UTC, Fank commented
@ctreminiom the reason why i wrote "deprecated" is because IDEs will display deprecation, which makes it easier for developer to identify it they are using deprecated functions.

Currently:
![image](https://github.com/ctreminiom/go-atlassian/assets/1900106/344ef854-fd52-41c4-834f-7196c4e64642)

By using "Deprecated" instead of "Not supported":
![image](https://github.com/ctreminiom/go-atlassian/assets/1900106/8fc7bca4-85f4-4238-b06d-8ef8c4f95a92)

2023-06-20 18:35 UTC, Fank commented
missing docs for https://docs.go-atlassian.io/jira-assets/objects#filter-objects

2023-06-23 07:13 UTC, ChristianKniep commented
Hey folks, digging deeper into how to populate assets it seems to me the cloud version prefers [External Imports](https://developer.atlassian.com/cloud/assets/imports-rest-api-guide/schema-and-mapping/).
It includes a process which creates a mapping (JSON) and uploads the data via rather simple http calls. The most work (it seems) is to create the types to generate the JSON and make the process robust. 
AFAIU this is not in scope for the `phase-1` of assets? I am going to give it a go anyway. I reckon contributing it to `go-atlassian` makes a lot of sense. Maybe in `phase-2`?  Fair assumptions?

2023-06-23 07:21 UTC, Fank commented
I would recommend splitting it in another part.
This PR is part of https://github.com/ctreminiom/go-atlassian/issues/202 and i would recommend comment it here or add another PR and add your request to it.
To be honest i have never seen that External Import. Our need was realtime updates Assets, i think thats the reason.

2023-06-25 05:02 UTC, ctreminiom reviewed
![image](https://github.com/ctreminiom/go-atlassian/assets/16035390/9ea5312b-33db-4d7e-90b3-60525908d0f0)

2023-06-25 05:08 UTC, ctreminiom commented
> missing docs for https://docs.go-atlassian.io/jira-assets/objects#filter-objects

Fixed 👍🏽

2023-06-25 05:10 UTC, ctreminiom commented
> Looks like there is something odd with the atlassian docs, https://developer.atlassian.com/cloud/assets/rest/api-group-object/#api-object-aql-post i see you implemented `ObjectListResult` as `ObjectListScheme` but if you check the properties of it ![image](https://user-images.githubusercontent.com/1900106/247233611-9d59b3fe-4eb2-4988-9fad-440c6925b713.png) it does not match not the example (which looks like the same from my tests) ![image](https://user-images.githubusercontent.com/1900106/247233857-a0fc4ea9-bc53-4330-8cfd-8b354f0439f3.png)
> 
> It looks correct for the AQL and IQL parts, but not for `/objects/aql`

My bad, I confused the `/object/navlist/aql `schema with ` /object/aql`, I've changed the schema on the commit [86656a3](https://github.com/ctreminiom/go-atlassian/pull/204/commits/86656a3598e740c865410b88f76709d18cf3a620)

2023-06-28 06:56 UTC, ctreminiom commented
> Hey folks, digging deeper into how to populate assets it seems to me the cloud version prefers [External Imports](https://developer.atlassian.com/cloud/assets/imports-rest-api-guide/schema-and-mapping/). It includes a process which creates a mapping (JSON) and uploads the data via rather simple http calls. The most work (it seems) is to create the types to generate the JSON and make the process robust. AFAIU this is not in scope for the `phase-1` of assets? I am going to give it a go anyway. I reckon contributing it to `go-atlassian` makes a lot of sense. Maybe in `phase-2`? Fair assumptions?

Hey @ChristianKniep, the _phase-1_ doesn't have the External Imports feature, it only adds the ability to manipulate the Objects, AQL, Icons, Object Attributes, Object Schemas and Object Types.

![image](https://github.com/ctreminiom/go-atlassian/assets/16035390/74556872-35d1-41ae-98f4-53214bf888c1)

I would suggest to you to create a new PR based on this one and map the External Import endpoints😄. 

![image](https://github.com/ctreminiom/go-atlassian/assets/16035390/2ccfab31-104a-4bec-8d32-ac1e2838b252)

@Fank there was some misunderstanding about the AQL service and the Object AQL services, but it's know fixed 👍🏽.

2023-07-12 06:40 UTC, ChristianKniep commented
Hey there, using the asset Client I notice that the URL is hard coded. For testing it would be nicer if the host is part of the `New` function like with the others.
```
diff --git a/assets/api_client_impl.go b/assets/api_client_impl.go
index 1831ad7..5ebe45f 100644
--- a/assets/api_client_impl.go
+++ b/assets/api_client_impl.go
*snip import changes*
 const DefaultAssetsSite = "https://api.atlassian.com/"
 
-func New(httpClient common.HttpClient) (*Client, error) {
+func New(httpClient common.HttpClient, site string) (*Client, error) {
 
        if httpClient == nil {
                httpClient = http.DefaultClient
        }
 
-       u, err := url.Parse(DefaultAssetsSite)
+       if site == "" {
+               return nil, model.ErrNoSiteError
+       }
+
+       if !strings.HasSuffix(site, "/") {
+               site += "/"
+       }
+
+       u, err := url.Parse(site)
+
        if err != nil {
                return nil, err
        }
```

2023-07-24 06:25 UTC, ctreminiom commented
@Fank @ChristianKniep do you have more feedback about this module?, just before the merging.

2023-08-03 13:52 UTC, ChristianKniep commented
@ctreminiom I do not, looking forward to it being merged.. :)

2023-08-06 16:59 UTC, Fank commented
@ctreminiom I would say it's good to go

2023-08-09 05:17 UTC, ctreminiom commented
Merging now then....

2023-08-09 05:17 UTC, merged