:sparkles: Added the Jira Workflow APISg
ctreminiom/go-atlassian pull request #299
Opened 2024-08-03 18:59 UTC by ctreminiom

2024-08-04 15:07 UTC, Fank requested changes

2024-08-04 15:07 UTC, Fank commented on jira/internal/workflow_impl.go
> +
Please add documentation

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	CustomIssueEventId string                             `json:"customIssueEventId,omitempty"`
```suggestion
	CustomIssueEventID string                             `json:"customIssueEventId,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	Id      string `json:"id,omitempty"`
```suggestion
	ID      string `json:"id,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	Id      string `json:"id,omitempty"`
```suggestion
	ID      string `json:"id,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	WorkflowIds          []string                                 `json:"workflowIds,omitempty"`
```suggestion
	WorkflowIDs          []string                                 `json:"workflowIds,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	ProjectId   string `json:"projectId,omitempty"`
```suggestion
	IssueTypeID string `json:"issueTypeId,omitempty"`
	ProjectID   string `json:"projectId,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	Id               string                           `json:"id,omitempty"`
```suggestion
	ID               string                           `json:"id,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	TaskId           string                           `json:"taskId,omitempty"`
```suggestion
	TaskID           string                           `json:"taskId,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	CreateUrl   string `json:"createUrl,omitempty"`
```suggestion
	CreateURL   string `json:"createUrl,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	EditUrl     string `json:"editUrl,omitempty"`
```suggestion
	EditURL     string `json:"editUrl,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	ViewUrl     string `json:"viewUrl,omitempty"`
```suggestion
	ViewURL     string `json:"viewUrl,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on pkg/infra/models/jira_workflow.go
> +	CustomIssueEventId string                             `json:"customIssueEventId,omitempty"`
```suggestion
	CustomIssueEventID string                             `json:"customIssueEventId,omitempty"`
```

2024-08-04 15:07 UTC, Fank commented on service/jira/workflow.go
> +	ValidateUpdateWorkflows(ctx context.Context, payload *model.ValidationOptionsForUpdateScheme) (*model.WorkflowValidationErrorListScheme, *model.ResponseScheme, error)
Please add documentation

2024-08-09 05:11 UTC, ctreminiom commented on jira/internal/workflow_impl.go
> +
Done @Fank!

2024-08-09 05:11 UTC, ctreminiom commented on service/jira/workflow.go
> +	ValidateUpdateWorkflows(ctx context.Context, payload *model.ValidationOptionsForUpdateScheme) (*model.WorkflowValidationErrorListScheme, *model.ResponseScheme, error)
Done @Fank!

2024-08-11 02:09 UTC, merged